In [1]:
import numpy as np
import numpy.linalg as nla
import numpy.random as random
import scipy.linalg as la
import scipy.sparse as sp

In [6]:
print(random.uniform(size = 10))

[0.64043044 0.16995743 0.98593776 0.2736787  0.96571637 0.36568223
 0.42012448 0.06764497 0.44574312 0.37161154]


In [22]:
N = 4
D = np.diag(random.uniform(size = N))
# construct random unitary matrices
Hmatrix = random.normal(size = (N, N)) + 1j*random.normal(size = (N, N))
Hmatrix = (Hmatrix + np.conj(Hmatrix).T)/2
Umatrix = la.expm(1j*Hmatrix)
Gamma = Umatrix @ D @ np.conj(Umatrix).T


[[ 0.00000000e+00+1.65653198e-17j -2.08166817e-17+2.94902991e-17j
  -1.73472348e-18+2.08166817e-17j  3.46944695e-18+2.77555756e-17j]
 [ 2.08166817e-17+2.94902991e-17j  0.00000000e+00+3.36613145e-19j
  -1.38777878e-17+2.77555756e-17j  0.00000000e+00-1.04083409e-17j]
 [ 1.73472348e-18+2.08166817e-17j  1.38777878e-17+2.77555756e-17j
   0.00000000e+00+1.51769665e-18j -3.46944695e-18+4.16333634e-17j]
 [-3.46944695e-18+2.77555756e-17j  0.00000000e+00-1.04083409e-17j
   3.46944695e-18+4.16333634e-17j  0.00000000e+00+9.20861965e-19j]]


In [34]:
# vectorizing kronecker products

# List of NumPy arrays
A = [np.array([[1, 2], [3, 4]]), np.array([[0, 1], [1, 0]])]

# Convert to NumPy array to enable broadcasting
A_arr = np.array(A, dtype=object)  # Using dtype=object since arrays have different contents
kron_vec = np.vectorize(np.kron, signature='(m,n),(p,q)->(mp,nq)')
kronecker_products = kron_vec(A_arr, A_arr)

# Print results
#print(kronecker_products.shape)  # Should be (len(A), len(A), ...)
print(kronecker_products)
print(np.kron([[1, 2], [3, 4]],[[1, 2], [3, 4]]))
print(np.kron([[0,1],[1,0]],[[0,1],[1,0]]))

[[[1 2 2 4]
  [3 4 6 8]
  [3 6 4 8]
  [9 12 12 16]]

 [[0 0 0 1]
  [0 0 1 0]
  [0 1 0 0]
  [1 0 0 0]]]
[[ 1  2  2  4]
 [ 3  4  6  8]
 [ 3  6  4  8]
 [ 9 12 12 16]]
[[0 0 0 1]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]]


In [35]:
import numpy as np
import time

# Generate a list of 10 random 4x4 matrices
N = 10
matrices = [np.random.rand(4, 4) for _ in range(N)]

# Convert to NumPy array (dtype=object needed for mixed-size arrays)
matrices_arr = np.array(matrices, dtype=object)

# Function to compute Kronecker product
def kron_product(A, B):
    return np.kron(A, B)

# Benchmark Explicit Loop
start_time = time.time()
loop_result = np.array([[np.kron(A, B) for B in matrices] for A in matrices])
loop_time = time.time() - start_time

# Benchmark np.vectorize
kron_vec = np.vectorize(kron_product, signature='(m,n),(p,q)->(mp,nq)')
start_time = time.time()
vectorized_result = kron_vec(matrices_arr[:, None], matrices_arr[None, :])
vectorized_time = time.time() - start_time

# Print results
print(f"Loop Execution Time: {loop_time:.5f} seconds")
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")
print("Results are equal:", np.allclose(loop_result, vectorized_result))

Loop Execution Time: 0.00363 seconds
Vectorized Execution Time: 0.00468 seconds


TypeError: ufunc 'isfinite' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [41]:
v = random.uniform(size = (1, 5))
u = random.uniform(size = (5,1))
print(type(u @ v))


<class 'numpy.ndarray'>


In [48]:
import numpy as np
from itertools import product

Lx, Ly = 10, 10  # Example values

nx = np.arange(-Lx/2, Lx/2, 1)
ny = np.arange(-Ly/2, Ly/2, 1)
kx = (2/Lx) * nx
ky = (2/Ly) * ny

# Swap ky and kx in product() so kx changes first
grid_points = list(product(kx, ky))  # CORRECT order: kx changes first

print(grid_points[:10])  # First 10 elements

[(-1.0, -1.0), (-1.0, -0.8), (-1.0, -0.6000000000000001), (-1.0, -0.4), (-1.0, -0.2), (-1.0, 0.0), (-1.0, 0.2), (-1.0, 0.4), (-1.0, 0.6000000000000001), (-1.0, 0.8)]


In [56]:
Lx = 5
Ly = 5
kx = (2/Lx)*np.arange(-Lx/2, Lx/2, 1)
ky = (2/Ly)*np.arange(-Ly/2, Ly/2, 1)
k_grid = np.array(list(product(ky, kx)))[:, ::-1]
print(k_grid)

[[-1.  -1. ]
 [-1.  -0.6]
 [-1.  -0.2]
 [-1.   0.2]
 [-1.   0.6]
 [-0.6 -1. ]
 [-0.6 -0.6]
 [-0.6 -0.2]
 [-0.6  0.2]
 [-0.6  0.6]
 [-0.2 -1. ]
 [-0.2 -0.6]
 [-0.2 -0.2]
 [-0.2  0.2]
 [-0.2  0.6]
 [ 0.2 -1. ]
 [ 0.2 -0.6]
 [ 0.2 -0.2]
 [ 0.2  0.2]
 [ 0.2  0.6]
 [ 0.6 -1. ]
 [ 0.6 -0.6]
 [ 0.6 -0.2]
 [ 0.6  0.2]
 [ 0.6  0.6]]
